DROP TABLE IF EXISTS membership
CASCADE;

CREATE TABLE membership
(
  id        SERIAL  PRIMARY KEY,
  user_id   INTEGER REFERENCES user ON DELETE CASCADE,
  org_id    INTEGER REFERENCES org ON DELETE CASCADE,
  is_active BOOLEAN DEFAULT true,
  is_admin  BOOLEAN DEFAULT false
);